---
- name: Configure EC2 tunnel instance
  hosts: all
  become: true
  vars:
    vault_addr: "https://vault.apps.okd.benrachmiel.org"
    # Set VAULT_TOKEN in environment
    kube_vip_ip: "192.168.1.200"
    gateway_ip: "192.168.1.240"
    gateway_nodeport_http: 30080
    gateway_nodeport_https: 30443
    wg_port: 51820
  roles:
    - wireguard
    - tcp-proxy
